my_sample_project/blog_app/urls.py
from django.urls import path
from .views import *

app_name="blog_app"

urlpatterns = [
    path('posts/', BlogListView.as_view(), name="posts"),
    path('my_posts/', MyPostsListView.as_view(), name="my_posts"),
    path('post/<int:year>/<int:month>/<int:day>/<slug:slug_id>', BlogDetailView.as_view(),name="post"),
    path('post/<int:pk>', BlogDetailView.as_view(),name="post_by_pk"),
    path('delete_post/<int:pk>', BlogDeleteView.as_view(),name="delete_post"),
    path('update_post/<int:pk>',BlogUpdateView.as_view() ,name="update_post"),
    path('create_post/', BlogPostCreateView.as_view() ,name="create_post"),
    path('post_comment/<int:post_id>', post_comment, name="post_comment"),
    path('share_by_email/<int:post_id>', share_by_email, name="share_by_email"),
    path('tag/<slug:tag_slug>/', post_list_by_tag, name='post_list_by_tag'),
]

my_sample_project/home_app/urls.py
from django.urls import path, include
from . import views

app_name = "home_app"

urlpatterns = [
    path('', views.home, name="home"),
    path('index', views.home, name="home"),
    path('register/', views.register, name='register'),
    path('open_page', views.open_page, name="open_page"),    
    path('closed_page', views.closed_page, name="closed_page"),  
    path('account/edit', views.edit_account, name="edit_account"),  
    # path('open_page', views.OpenView.as_view(), name='open_page'),
    # path('apereo', views.ApereoView.as_view(), name='apereo'),
    # path('manual', views.ManualProtect.as_view(), name='manual'),
    # path('protect', views.ProtectView.as_view(), name='protect'),
    # path('python', views.DumpPython.as_view(), name='python'),
]

my_sample_project/my_sample_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home_app.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('blog_app.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('bookmark_app.urls', namespace='images')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

my_sample_project/home_app/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Profile(models.Model):
    birthdate = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d/', 
                              blank=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    def __str__(self):
        return f'Profile of {self.user.username}'

my_sample_project/home_app/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.conf import settings

from .models import Profile

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(
        label='Password',
        widget=forms.PasswordInput
    )
    password2 = forms.CharField(
        label='Repeat password',
        widget= forms.PasswordInput
    )
    
    class Meta:
        model = get_user_model()
        fields = ['username', 'first_name', 'email']
    
class EditUserForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']
        
class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['date_of_birth', 'photo']

my_sample_project/home_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.contrib.auth import login

from .forms import *
from .models import Profile

# Create your views here.
def home(request):
    return render(request, "home_app/home.html")

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            Profile.objects.create(user=user)
            login(request,
                  user,
                  backend='home_app.authentication.EmailAuthBackend')  # Log in the user immediately after registration
            return redirect('home_app:home')  # Redirect to a 'home' page after registration
    else:
        form = UserCreationForm()
    return render(request, 'registration/register.html', {'form': form})

def open_page(request):
    return HttpResponse("<h1>Open page</h1><p> This page is available to everyone without any restrictions. Enjoy!</p>")

@login_required
def closed_page(request):
    return HttpResponse("<h1>Closed page</h1><p>This page is available only to authorized users. <br> You are definitely authorized if you see this page.</p>")

@login_required
def edit(request):
    if request.method == "POST":
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile, data=request.POST)
        
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    
    return render(request, 
                  'registration/account_edit.html',
                  {"user_form" : user_form, 
                   "profile_form": profile_form 
    })

my_sample_project/home_app/templates/home_app/base.html
{% block content %}
{% endblock%}

my_sample_project/home_app/templates/home_app/base_bootstrap.html
<!DOCTYPE html>
<html>
<head>

<title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

{% block head %} {% endblock %}

</head>

<body>
<div class="container">
{% block navbar %} {% endblock %}
{% block content %}{% endblock %}
</div>
{% block footer %} {% endblock %}
</body>
</html>

my_sample_project/home_app/templates/home_app/home.html
{% block content %}


{% if user.is_authenticated %}
<h1>Hello, {{ user.username }}!</h1>
{% if user.profile.photo %}
<img src="{{user.profile.photo.url}}" />
{% endif %}

<p>Authenticated as
    <pre>
    Username: {{ user.username }}
    Full name: {{ user.get_full_name }}
    Email: {{ user.email }}
    Id: {{ user.id }}
    Is admin: {{user.is_superuser}}
    </pre>
</p>

<form action="{% url "logout" %}" method="post">
    <label>You are logged in. You can Logout:</label>
    <button type="submit">Logout</button>
    {% csrf_token %}
</form>
<a href="{% url 'home_app:edit_account' %}">Edit account</a>
{% else %}
<h1>Hello, Guest!</h1>
<p>You are not logged in</p>
<p>You can <a href="{% url 'login' %}?next={{ request.path }}">Login</a> or 
    <a href="{% url 'home_app:register' %}?next={{ request.path }}">Register</a> if you like.</p>
{% endif %}

<h3>Site map:</h3>
<ul>
    <li>
        Go to <a href="{% url 'home_app:open_page' %}">{% url 'home_app:open_page' %}</a>
            (no login required)
    </li>
    <li>
        Go to <a href="{% url 'home_app:closed_page' %}">{% url 'home_app:closed_page' %}</a>
            (login required: protected by login_required decorator)
    </li>
</ul>

{% endblock%}