my_sample_project/blog_app/urls.py
from django.urls import path
from .views import *

app_name="blog_app"

urlpatterns = [
    path('posts/', BlogListView.as_view(), name="posts"),
    path('my_posts/', MyPostsListView.as_view(), name="my_posts"),
    path('post/<int:year>/<int:month>/<int:day>/<slug:slug_id>', BlogDetailView.as_view(),name="post"),
    path('post/<int:pk>', BlogDetailView.as_view(),name="post_by_pk"),
    path('delete_post/<int:pk>', BlogDeleteView.as_view(),name="delete_post"),
    path('update_post/<int:pk>',BlogUpdateView.as_view() ,name="update_post"),
    path('create_post/', BlogPostCreateView.as_view() ,name="create_post"),
    path('post_comment/<int:post_id>', post_comment, name="post_comment"),
    path('share_by_email/<int:post_id>', share_by_email, name="share_by_email"),
    path('tag/<slug:tag_slug>/', post_list_by_tag, name='post_list_by_tag'),
]

my_sample_project/my_sample_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home_app.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('blog_app.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('bookmark_app.urls', namespace='images')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

my_sample_project/blog_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from taggit.managers import TaggableManager

class PublishedPostsManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=BlogPost.PublicationStatus.PUBLISHED)

        
class BlogPost(models.Model):
    class Meta:
        ordering = ['-published_at']
    
    class PublicationStatus(models.TextChoices):
        DRAFT = "D", _("Draft")
        PUBLISHED = "P", _("Published")

    status = models.CharField(
        max_length=1,
        choices=PublicationStatus,
        default=PublicationStatus.DRAFT,
    )
    
    title = models.CharField(max_length=100)
    text = models.TextField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(unique_for_date = 'created_at', blank=False)
    published_at = models.DateTimeField(default=timezone.now)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    objects = models.Manager()
    published_objects = PublishedPostsManager()
    
    tags = TaggableManager()
    
    def __str__(self):
        return self.title + " | by " + self.owner.username
    
    def get_absolute_url(self):
        # return reverse("post/<int:pk>", kwargs={"pk": self.pk})
        return reverse(
            'blog_app:post',
            args=[
                self.created_at.year,
                self.created_at.month,
                self.created_at.day,
                self.slug
                ]
            )
    
    def save(self, *args, **kwargs):
        if self.pk:
            previous = BlogPost.objects.get(pk=self.pk)
            if previous.status == BlogPost.PublicationStatus.DRAFT and \
                self.status == BlogPost.PublicationStatus.PUBLISHED:
            
                self.published_at = timezone.now()
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)
        

class Comment(models.Model):
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ['created_at']
        indexes = [models.Index(fields=['created_at']),]
    
    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

my_sample_project/blog_app/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        
class EmailForm(forms.Form):
    email_to = forms.EmailField()
    subject = forms.CharField(max_length=120)
    text = forms.CharField(widget=forms.Textarea)

my_sample_project/blog_app/views.py
from django.views.generic.list import ListView
from django.views.generic import DetailView
from django.views.decorators.http import require_POST
from django.urls import reverse_lazy
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.core.mail import send_mail
from django.contrib import messages

from .ownerviews import *
from .forms import *
from .models import BlogPost

class BlogListView(ListView):
    model = BlogPost
    paginate_by = 5
    queryset = BlogPost.published_objects.all()
    
class MyPostsListView(ListView):
    model = BlogPost
    paginate_by = 5
    
    def get_queryset(self):
        return super().get_queryset().filter(owner = self.request.user)

class BlogDetailView(DetailView):
    model = BlogPost
    
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx["comment_form"] = CommentForm()
        return ctx
    
    def get_object(self, queryset=None):
        pk = self.kwargs.get("pk")
        
        year = self.kwargs.get("year")
        month = self.kwargs.get("month")
        day = self.kwargs.get("day")
        slug_id = self.kwargs.get("slug_id")

        if pk:
            return get_object_or_404(self.model, pk=pk)
        elif slug_id:
            return get_object_or_404(self.model, created_at__year=year, created_at__month=month, created_at__day=day, slug = slug_id)
        else:
            raise Http404("No object found matching the provided criteria.")

class BlogDeleteView(OwnerDeleteView):
    model = BlogPost
    success_url = reverse_lazy("blog_app:posts")
   
class BlogPostCreateView(OwnerCreateView):
    model = BlogPost
    fields = ["title", "text", "status"]
    success_url = reverse_lazy("blog_app:posts")
    
class BlogUpdateView(OwnerUpdateView):
    model = BlogPost
    success_url = reverse_lazy("blog_app:posts")
    fields = ["title", "text", "status"]
    
@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(BlogPost, id=post_id) #,status=BlogPost.PublicationStatus.PUBLISHED
    comment = None

    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.blogpost = post
        comment.user = request.user
        comment.save()
        
        messages.add_message(request, messages.WARNING, "Comment was added.")
        
    return render(request,
                  'blog_app/comment.html',
                  {
                    'blogpost': post,
                    'form': form,
                    'comment': comment
                  }
                  )
    
def share_by_email(request, post_id):
    form = None
    if request.method == "POST":
        form = EmailForm(request.POST)
        if (form.is_valid()):
            email_to = form.cleaned_data["email_to"]
            subject = form.cleaned_data["subject"]
            text = form.cleaned_data["text"]
            
            send_mail(
                subject,
                text,
                from_email=None,
                recipient_list=[email_to],
                fail_silently=False,
            )    
    else:
        form = EmailForm()
    
    ctx = {"form": form }

    return render(request, "blog_app/share_post.html", ctx)

my_sample_project/blog_app/templates/blog_app/base.html
<!DOCTYPE html>
<html>
<head>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

{% block head %} 
{%include 'blog_app/header.html' %}
{% endblock %}

</head>

<body>
<div class="container">
{% block navbar %} {% endblock %}
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
{% endblock %}
</div>
{% block footer %} {% endblock %}
</body>
</html>

my_sample_project/blog_app/templates/blog_app/blogpost_confirm_delete.html
{%extends 'blog_app/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ blogpost.title }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>
{% endblock %}

my_sample_project/blog_app/templates/blog_app/blogpost_detail.html
{%extends 'blog_app/base.html' %}

{% block content %}
<h1>{{blogpost.title}} </h1>
<p>
{{blogpost.text}}
</p>

<p class="text-muted">
    <i>Author: {{blogpost.owner}}</i><br/>
    <i>Status: {{blogpost.get_status_display}}</i><br/>
    <i>Created at: {{blogpost.updated_at}}</i><br/>
    <i>Published at: {{blogpost.published_at}}</i><br/>
    <i>Updated at: {{blogpost.updated_at}}</i>
</p>

{% with blogpost.comments.count as total_comments %}
<h2>
{{ total_comments }} comment{{ total_comments|pluralize }}:
</h2>
{% endwith %}


{%for comment in blogpost.comments.all%}
<div class="comment">
    <p class="info">
    Comment {{ forloop.counter }} by {{ comment.name }}
    {{ comment.created }}
    </p>
    {{ comment.body|linebreaks }}
</div>
{% empty %}
    <p>There are no comments.</p>
{% endfor %}

{%include 'blog_app/includes/comment_form.html' with post=blogpost %}

<h2>Similar posts</h2>
{% for blogpost in similar_posts %}
<p>
<a href="{{ blogpost.get_absolute_url }}">{{ blogpost.title }}</a>
</p>
{% empty %}
There are no similar posts yet.
{% endfor %}

my_sample_project/blog_app/templates/blog_app/blogpost_form.html
{%extends 'blog_app/base.html' %}

{% load crispy_forms_tags %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form | crispy}}
    <input type="submit" value="Update">
 </form>
 {% endblock %}

my_sample_project/blog_app/templates/blog_app/blogpost_list.html
{%extends 'blog_app/base.html' %}

{%block content%}
<h2>All posts:</h2>
{% comment %} <ul> {% endcomment %}
   {% for blogpost in page_obj %}
   {% comment %} <li> {% endcomment %}
   <h2><a href="{{ blogpost.get_absolute_url }}">{{ blogpost.title }}</a></h2>
   <p class="text-muted">
    Published {{ blogpost.published_at }} by {{ blogpost.owner }}
    </p>
   {{ blogpost.text|truncatewords:30 }}

   {% if blogpost.owner == user %}
   ( <a href="{% url 'blog_app:update_post' blogpost.id %}">
      Edit</a> |
   <a href="{% url 'blog_app:delete_post' blogpost.id %}">
      Delete</a>)
   {% endif %}
   <br/>
   {% for tag in blogpost.tags.all %}
    <a href="{% url "blog_app:post_list_by_tag" tag.slug %}">
    {{ tag.name }}
    </a>{% if not forloop.last %}, {% endif %}
    {% endfor %}
   </li>
   {% endfor %}
   
{% comment %} </ul> {% endcomment %}

<div class="pagination">
   <span class="step-links">
       {% if page_obj.has_previous %}
           <a href="?page=1">&laquo; first</a>
           <a href="?page={{ page_obj.previous_page_number }}">previous</a>
       {% endif %}

       <span class="current">
           Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
       </span>

       {% if page_obj.has_next %}
           <a href="?page={{ page_obj.next_page_number }}">next</a>
           <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
       {% endif %}
   </span>
</div>
{%endblock%}

my_sample_project/blog_app/templates/blog_app/comment.html
{% extends "blog_app/base.html" %}
{% block title %}Add a comment{% endblock %}
{% block content %}
{% if comment %}
<h2>Your comment has been added.</h2>
<p><a href="{{ blogpost.get_absolute_url }}">Back to the post</a></p>
{% else %}
{% include "blog_app/includes/comment_form.html" %}
{% endif %}
{% endblock %}

my_sample_project/blog_app/templates/blog_app/header.html
<nav class="navbar navbar-expand-lg navbar-light" style="border-radius:10px !important; background-color: #e3f2fd;">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'blog_app:posts' %}">{{ settings.APP_NAME }}</a>
    <ul class="navbar-nav">
      {% url 'blog_app:posts' as x %}
      <li {% if request.get_full_path == x %}class="active"{% endif %}>
          <a class="nav-link" href="{% url 'blog_app:posts' %}" role="button">All posts</a></li>
          <li {% if request.get_full_path == x %}class="active"{% endif %}>
            <a class="nav-link" href="{% url 'blog_app:my_posts' %}" role="button">My posts</a></li>
    </ul>
    <ul class="navbar-nav">
      {% if user.is_authenticated %}
      <li>
         <a class="nav-link" href="{% url 'blog_app:create_post' %}">Create Post</a>
      </li>
      <li class="nav-item dropdown">
         <a class="nav-link dropdown-toggle" href="#" id="rightnavDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        </a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="rightnavDropdown">
            <form action="{% url "logout" %}" method="post">
                <button class="btn btn-link" type="submit">{{user.username}} |Logout</button>
                {% csrf_token %}
            </form>
            {% comment %} <li><a class="dropdown-item" href="{% url 'logout' %}?next={% url 'blog_app:posts' %}">Logout</a></li> {% endcomment %}
        </ul>
       </li>
       {% else %}
       <li class="nav-item"><a class="nav-link" href="{% url 'login' %}?next={% url 'blog_app:posts' %}">Login</a></li>
       {% endif %}
    </ul>
  </div>
</nav>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% comment %} <ul>
    <li><a href="{% url 'blog_app:posts'%}">All posts</a></li>
    <li><a href="{% url 'blog_app:my_posts'%}">My posts</a></li>
    <li><a href="{% url 'blog_app:create_post'%}">Create posts</a></li>
    {% if user.is_authenticated %}
    <li>
        <form action="{% url "logout" %}" method="post">
            <button type="submit">{{user.username}} |Logout</button>
            {% csrf_token %}
        </form>
    </li>
    {% else %}
    <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
    {% endif%}
</ul> {% endcomment %}

my_sample_project/blog_app/templates/blog_app/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

my_sample_project/blog_app/templates/blog_app/share_post.html
{% extends "home_app/base_bootstrap.html" %}

{% load crispy_forms_tags %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{form | crispy}}
    <input type="submit" value="Send e-mail">
</form>

{% endblock %}